<<<<<<< Updated upstream:src/Fornecedores.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
=======
import javax.swing.*;
import java.util.ArrayList;
>>>>>>> Stashed changes:src/Produtos.java

/**
 *
 * @author bell
 */
public class Produtos extends javax.swing.JFrame {
    ProdutoModel model = new ProdutoModel();
    /**
     * Creates new form Produtos
     */
    public Produtos() {
        initComponents();
        tbProdutos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtValorUnitario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        btnCriar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        optUnidade = new javax.swing.JComboBox<>();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Gerenciamento de Produtos");

        jLabel2.setText("ID");

        jLabel3.setText("Nome");

        jLabel4.setText("Descrição");

        jLabel5.setText("Quantidade");

        jLabel6.setText("Unidade");

        jLabel7.setText("Valor Unitário");

        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
<<<<<<< Updated upstream:src/Fornecedores.java
        jScrollPane1.setViewportView(tbFornecedores);
=======
        tbProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProdutos);
>>>>>>> Stashed changes:src/Produtos.java

        btnCriar.setText("Criar");
        btnCriar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCriarMouseClicked(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeletarMouseClicked(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        optUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CX", "PCT", "UN", "MT" }));

        btnVoltar.setText("Voltar");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel7)
                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                                                .addGap(51, 51, 51)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(txtID)
                                                                        .addComponent(txtNome)
                                                                        .addComponent(txtDescricao)
                                                                        .addComponent(txtQuantidade)
                                                                        .addComponent(txtValorUnitario)
                                                                        .addComponent(optUnidade, 0, 266, Short.MAX_VALUE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnCriar)
                                                                .addGap(86, 86, 86)
                                                                .addComponent(btnEditar)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                                                .addComponent(btnDeletar)))
                                                .addGap(63, 63, 63)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnVoltar)
                                                .addGap(217, 217, 217)
                                                .addComponent(jLabel1)))
                                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(btnVoltar))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(optUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(txtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(92, 92, 92)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnCriar)
                                                        .addComponent(btnDeletar)
                                                        .addComponent(btnEditar)))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void btnCriarMouseClicked(java.awt.event.MouseEvent evt) {
        String txtid = txtID.getText();
        String txtquantidade = txtQuantidade.getText();
        String txtvalorunitario = txtValorUnitario.getText();
        int id = Integer.parseInt(txtID.getText());
        String nome = txtNome.getText();
<<<<<<< Updated upstream:src/Fornecedores.java
        int cpf = Integer.parseInt(txtCPF.getText());
        String logradouro = txtLogradouro.getText();
        String bairro = txtBairro.getText();
        String cidade = txtCidade.getText();
        String estado = txtEstado.getText();
        String telefone = txtTelefone.getText();
        String email = txtEmail.getText();
=======
        String descricao = txtDescricao.getText();
        int quantidade = Integer.parseInt(txtQuantidade.getText());
        String unidade = optUnidade.getSelectedItem()+"";
        double valorUnitario = Double.parseDouble(txtValorUnitario.getText());
>>>>>>> Stashed changes:src/Produtos.java

        if(nome.length() == 0 || descricao.length() == 0 || Double.valueOf(txtvalorunitario).isNaN() || txtquantidade.length() == 0 || txtid.length() == 0) {
            JOptionPane.showMessageDialog(this, "Campos não preenchidos!");
        } else {
            if(verificarId(id)) {
                Produto p = new Produto(id, nome, descricao, quantidade, unidade, valorUnitario);

                this.model.cadastrarProduto(p);

                LimparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "ID já utilizada!");
            }
        }
    }

    public void LimparCampos() {
        txtID.setText("");
        txtNome.setText("");
        txtDescricao.setText("");
        txtQuantidade.setText("");
        optUnidade.setSelectedItem("");
        txtValorUnitario.setText("");
    }

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {
<<<<<<< Updated upstream:src/Fornecedores.java
        // TODO add your handling code here:
    }

    private void btnDeletarMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
=======
        String txtvalorunitario = txtValorUnitario.getText();
        String txtquantidade = txtQuantidade.getText();
        String txtid = txtID.getText();
        int id = Integer.parseInt(txtID.getText());
        String nome = txtNome.getText();
        String descricao = txtDescricao.getText();
        int quantidade = Integer.parseInt(txtQuantidade.getText());
        String unidade = optUnidade.getSelectedItem()+"";
        double valorUnitario = Double.parseDouble(txtValorUnitario.getText());
        int index = tbProdutos.getSelectedRow();

        if(nome.length() == 0 || descricao.length() == 0 || Double.valueOf(txtvalorunitario).isNaN() || txtquantidade.length() == 0 || txtid.length() == 0) {
            JOptionPane.showMessageDialog(this, "Campos não preenchidos!");
        } else {
            if(verificarId(id)) {
                JOptionPane.showMessageDialog(this, "ID não existente!");
            } else {
                Produto p = new Produto(id, nome, descricao, quantidade, unidade, valorUnitario);

                this.model.editarProduto(index, p);

                LimparCampos();
            }
        }
    }

    public boolean verificarId(int id) {
        ArrayList<Produto> produtos = model.listaProdutos();
        for(Produto p: produtos) {
            if (p.getId() == id) {
                return false;
            }
        }
        return true;
    }

    private void btnDeletarMouseClicked(java.awt.event.MouseEvent evt) {
        int index = tbProdutos.getSelectedRow();

        if(JOptionPane.showConfirmDialog(this, "Deseja realmente remover o produto?", "Produto", JOptionPane.YES_NO_OPTION) == 0) {
            this.model.deletarProdutos(index);

            LimparCampos();
        }
    }

    private void tbProdutosMouseClicked(java.awt.event.MouseEvent evt) {
        int index = tbProdutos.getSelectedRow();
        Produto p = this.model.returnProduto(index);

        txtID.setText(String.valueOf(p.getId()));
        txtNome.setText(p.getNome());
        txtDescricao.setText(p.getDescricao());
        txtQuantidade.setText(String.valueOf(p.getQuantidade()));
        optUnidade.setSelectedItem(p.getQuantidade());
        txtValorUnitario.setText(String.valueOf(p.getValorUnitario()));
>>>>>>> Stashed changes:src/Produtos.java
    }

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {
        Menu m = new Menu();
        this.dispose();
        m.setVisible(true);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> optUnidade;
    private javax.swing.JTable tbProdutos;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValorUnitario;
    // End of variables declaration
}
